// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:new_project/network/model/result_model.dart';

// Will be generated by dart_mappable
part 'all_data_model.mapper.dart';

@MappableClass()
/// this model for all data came from api  
class AllDataModel with AllDataModelMappable {

  @MappableField(key: 'num_results')
  final int numResults;
  final List<ResultModel> results;

  AllDataModel({
    required this.numResults,
    required this.results,
  });
}