// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';
import 'package:new_project/network/model/metadata_model.dart';

// Will be generated by dart_mappable
part 'media_model.mapper.dart';

@MappableClass()
/// this model for media model and it contains necessary data for 
class MediaModel with MediaModelMappable {
  final String type;
  final String? subtype;
  final String? caption;
  final String? copyright;
  
  @MappableField(key: 'media-metadata')
  final List<MetadataModel> mediaMetadata;

  MediaModel({
    required this.type,
    this.subtype,
    this.caption,
    this.copyright,
    required this.mediaMetadata,
  });
}
