// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'metadata_model.mapper.dart';

@MappableClass()
/// this model is for metadata 
class MetadataModel with MetadataModelMappable {
  final String url;
  final num? height;
  final num? width;

  MetadataModel({
    required this.url,
    this.height,
    this.width,
  });
}